version: '3'

services:

  database:
    image: 'postgres:13.1-alpine'
    container_name: database-container
    environment:
      - POSTGRES_DB=d2dj138qsd6s51
      - POSTGRES_USER=saegkasotzymf
      - POSTGRES_PASSWORD=5b22d826fe9cc38ea066acfbc0856431858a9f2dae4f739b24be3a54270560e1
    networks:
      default:


  pharmacy-service:
    image: dians_proekt.azurecr.io/pharmacy-service:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-54-200-114-48.compute-1.amazonaws.com:5432/d2bh038qqi8s04
      - SPRING_DATASOURCE_USERNAME=saegkasotzymf
      - SPRING_DATASOURCE_PASSWORD=5b22d826fe9cc38ea066acfbc0856431858a9f2dae4f739b24be3a54270560e1
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - pharmacyapi
